/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.11
 * Generated at: 2019-04-30 03:01:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>主要内容区main</title>\r\n");
      out.write("<link href=\"css/css.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"css/main.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"images/main/favicon.ico\" />\r\n");
      out.write("<style>\r\n");
      out.write("body{overflow-x:hidden; background:#f2f0f5; padding:15px 0px 10px 5px;}\r\n");
      out.write("#main{ font-size:14px;}\r\n");
      out.write("#main span.time{ font-size:28px; color:#528dc5; width:100%; padding-bottom:10px; float:left}\r\n");
      out.write("#main div.top{ width:95%; background:url(images/main/main_r2_c2.jpg) no-repeat 0 10px; padding:0 0 0 15px; line-height:35px; float:left}\r\n");
      out.write("#main div.sec{ width:95%; background:url(images/main/main_r2_c2.jpg) no-repeat 0 15px; padding:0 0 0 15px; line-height:35px; float:left}\r\n");
      out.write(".left{ float:left}\r\n");
      out.write("#main div a{ float:left}\r\n");
      out.write("#main span.num{  font-size:30px; color:#538ec6; font-family:\"Georgia\",\"Tahoma\",\"Arial\";}\r\n");
      out.write(".left{ float:left}\r\n");
      out.write("div.main-tit{ font-size:14px; font-weight:bold; color:#4e4e4e; background:url(images/main/main_r4_c2.jpg) no-repeat 0 33px; width:100%; padding:30px 0 0 20px; float:left}\r\n");
      out.write("div.main-con{ width:100%; float:left; padding:10px 0 0 20px; line-height:36px;}\r\n");
      out.write("div.main-corpy{ font-size:14px; font-weight:bold; color:#4e4e4e; background:url(images/main/main_r6_c2.jpg) no-repeat 0 33px; width:100%; padding:30px 0 0 20px; float:left}\r\n");
      out.write("div.main-order{ line-height:30px; padding:10px 0 0 0;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--main_top-->\r\n");
      out.write("<table width=\"99%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" id=\"main\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td colspan=\"2\" align=\"left\" valign=\"top\">\r\n");
      out.write("\t<span class=\"time\">Solar</span>\r\n");
      out.write("    <div class=\"top\"><span class=\"left\">这是一款高效习惯养成的App，结合了科学的番茄工作法，有序的计划制定，任务管理等功能，将你的工作和生活中的待办任务与目标技能关联起来，让你做过的事务都成为积累技能成长的一部分。</span></div>\r\n");
      out.write("    <div class=\"sec\">通过丰富的图表统计，简洁的事务提醒，为你直观展示你对时间的管理情况，打造一款全方位的实用性时间管理工具。</div>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td align=\"left\" valign=\"top\" width=\"50%\">\r\n");
      out.write("    <div class=\"main-tit\">网站信息</div>\r\n");
      out.write("    <div class=\"main-con\">\r\n");
      out.write("会员注册：开启<br/>\r\n");
      out.write("会员投稿：开启<br/>\r\n");
      out.write("管理员个数：<font color=\"#538ec6\"><strong>6</strong></font> 人<br/>\r\n");
      out.write("登陆者IP：192.168.1.156<br/>\r\n");
      out.write("程序编码：UTF-8<br/>\r\n");
      out.write("    </div>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td align=\"left\" valign=\"top\" width=\"49%\">\r\n");
      out.write("    <div class=\"main-tit\">服务器信息</div>\r\n");
      out.write("    <div class=\"main-con\">\r\n");
      out.write("服务器软件：Apache Tomcat/9.0.11 (Win64) <br/>\r\n");
      out.write("Java版本：5.2.5<br/>\r\n");
      out.write("MYSQL版本：MySQL5.5.6<br/>\r\n");
      out.write("魔术引用：开启 (建议开启)<br/>\r\n");
      out.write("使用域名：192.168.1.124 <br/>\r\n");
      out.write("    </div>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td colspan=\"2\" align=\"left\" valign=\"top\">\r\n");
      out.write("    <div class=\"main-corpy\">系统提示</div>\r\n");
      out.write("    <div class=\"main-order\">1=>如您在使用过程有发现出错请及时与我们取得联系；为保证您得到我们的后续服务，强烈建议您购买我们的正版系统或向我们定制系统！<br/>\r\n");
      out.write("2=>强烈建议您将IE7以上版本或其他的浏览器</div>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
