/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.11
 * Generated at: 2019-06-11 07:48:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;

public final class updateimagescore_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>主要内容区main</title>\r\n");
      out.write("<link href=\"css/css.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"css/main.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"images/main/favicon.ico\" />\r\n");
      out.write("<style>\r\n");
      out.write("body{overflow-x:hidden; background:#f2f0f5; padding:15px 0px 10px 5px;}\r\n");
      out.write("#searchmain{ font-size:12px;}\r\n");
      out.write("#search{ font-size:12px; background:#548fc9; margin:10px 10px 0 0; display:inline; width:100%; color:#FFF; float:left}\r\n");
      out.write("#search form span{height:40px; line-height:40px; padding:0 0px 0 10px; float:left;}\r\n");
      out.write("#search form input.text-word{height:24px; line-height:24px; width:180px; margin:8px 0 6px 0; padding:0 0px 0 10px; float:left; border:1px solid #FFF;}\r\n");
      out.write("#search form input.text-but{height:24px; line-height:24px; width:55px; background:url(images/main/list_input.jpg) no-repeat left top; border:none; cursor:pointer; font-family:\"Microsoft YaHei\",\"Tahoma\",\"Arial\",'宋体'; color:#666; float:left; margin:8px 0 0 6px; display:inline;}\r\n");
      out.write("#search a.add{ background:url(images/main/add.jpg) no-repeat -3px 7px #548fc9; padding:0 10px 0 26px; height:40px; line-height:40px; font-size:14px; font-weight:bold; color:#FFF; float:right}\r\n");
      out.write("#search a:hover.add{ text-decoration:underline; color:#d2e9ff;}\r\n");
      out.write("#main-tab{ border:1px solid #eaeaea; background:#FFF; font-size:12px;}\r\n");
      out.write("#main-tab th{ font-size:12px; background:url(images/main/list_bg.jpg) repeat-x; height:32px; line-height:32px;}\r\n");
      out.write("#main-tab td{ font-size:12px; line-height:40px;}\r\n");
      out.write("#main-tab td a{ font-size:12px; color:#548fc9;}\r\n");
      out.write("#main-tab td a:hover{color:#565656; text-decoration:underline;}\r\n");
      out.write(".bordertop{ border-top:1px solid #ebebeb}\r\n");
      out.write(".borderright{ border-right:1px solid #ebebeb}\r\n");
      out.write(".borderbottom{ border-bottom:1px solid #ebebeb}\r\n");
      out.write(".borderleft{ border-left:1px solid #ebebeb}\r\n");
      out.write(".gray{ color:#dbdbdb;}\r\n");
      out.write("td.fenye{ padding:10px 0 0 0; text-align:right;}\r\n");
      out.write(".bggray{ background:#f9f9f9}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

  String id=request.getParameter("imageid");
  int imageid=Integer.parseInt(id);

      out.write("\r\n");
      out.write("<!--main_top-->\r\n");
      out.write("<table width=\"99%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" id=\"searchmain\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"99%\" align=\"left\" valign=\"top\">您的位置：修改图片积分</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td align=\"left\" valign=\"top\">\r\n");
      out.write("    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" id=\"search\">\r\n");
      out.write("  \t\t<tr>\r\n");
      out.write("   \t\t <td width=\"90%\" align=\"left\" valign=\"middle\">\r\n");
      out.write("\t         <form method=\"post\" action=\"\">\r\n");
      out.write("\t         <span>修改图片号为");
      out.print(imageid );
      out.write("的积分：</span>\r\n");
      out.write("\t         \r\n");
      out.write("\t         </form>\r\n");
      out.write("         </td>\r\n");
      out.write("  \t\t  <td width=\"10%\" align=\"center\" valign=\"middle\" style=\"text-align:right; width:150px;\"></td>\r\n");
      out.write("  \t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td align=\"left\" valign=\"top\">\r\n");
      out.write("    <form action=\"UpdateImageScoreServlet\">\r\n");
      out.write("          图片编号：<input type=\"text\" name=\"imageid\" value=\"");
      out.print(imageid );
      out.write("\"><br>\r\n");
      out.write("          图片积分：  <input type=\"text\" name=\"score\"><br>\r\n");
      out.write("                 <input type=\"submit\" value=\"确认修改\">\r\n");
      out.write("               \r\n");
      out.write("   </form>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
