/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.11
 * Generated at: 2018-12-28 04:51:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class coursecomment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1544956724000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1544330974000L));
    _jspx_dependants.put("jar:file:/D:/EShareClass/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/plailing/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1064305020000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1545913174000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("<title>coursecomment</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon.ico\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/font-awesome//4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/highlight.js/9.8.0/monokai-sublime.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/css/libs/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"app/css/libs/katex/0.6.0/katex.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/css/libs/videojs/5.11.7/video-js.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/css/dest/styles.css?=2016121272249\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/restatic/js/libs/marked/katex/katex.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/comment.css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-1.12.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.flexText.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/jquery/2.2.4/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function isJoin(email1,courseId,uploadId){\r\n");
      out.write("\tif(email1==''){\r\n");
      out.write("\t\talert(\"请您登录后再加入课程！\")\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tvar con=confirm(\"您加入此课程需扣除您账户余额，是否确定加入此课程？\");\r\n");
      out.write("\t\tif(con==true){\t\t\t\r\n");
      out.write("\t\t\tvar xmlhttp;\r\n");
      out.write("\t\t\tif(window.XMLHttpRequest){\r\n");
      out.write("\t\t\t\txmlhttp=new XMLHttpRequest();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\txmlhttp=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\txmlhttp.open(\"GET\",\"detailJoin?courseId=\"+courseId+\"&uploadUser=\"+uploadId,true);\r\n");
      out.write("\t\t\txmlhttp.send();\r\n");
      out.write("\t\t\txmlhttp.onreadystatechange=function(){\r\n");
      out.write("\t\t\t\tif(xmlhttp.readyState==4 && xmlhttp.status==200){\r\n");
      out.write("\t\t\t\t\tvar res=xmlhttp.responseText;\r\n");
      out.write("\t\t\t\t\tif(res==\"fail\"){\r\n");
      out.write("\t\t\t\t\t\talert(\"您已加入过此课程，不能重复加入！\");\r\n");
      out.write("\t\t\t\t\t}else if(res==\"checkfail\"){\r\n");
      out.write("\t\t\t\t\t\talert(\"您的余额不足，请先去个人中心充值后在进行购买！\");\r\n");
      out.write("\t\t\t\t\t}else if(res==\"buy\"){\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"joinflag\").value=1;\r\n");
      out.write("\t\t\t\t\t\talert(\"购买成功，钱数已从余额中扣除！\");\r\n");
      out.write("\t\t\t\t\t}else if(res==\"emailempty\"){\r\n");
      out.write("\t\t\t\t\t\talert(\"请您先进行登录，如果没有登录不能收藏此课程!\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function insertc(btn2,textbox,courseId,courseCommentId){\r\n");
      out.write("\t\tvar allcontent=document.getElementsByName(\"courseCommentText\");\r\n");
      out.write("\t\t\tfor(var i=0;i<allcontent.length;i++){\r\n");
      out.write("\t\t\tif(allcontent[i].value!=''){\r\n");
      out.write("\t\t\t\ttextbox.style.display = \"none\";\r\n");
      out.write("\t\t\t\tbtn2.style.display = \"none\";\r\n");
      out.write("\t\t\t\tvar content=allcontent[i].value;\r\n");
      out.write("\t\t\t\tvar xmlhttp;\r\n");
      out.write("\t\t\t\tif(window.XMLHttpRequest){\r\n");
      out.write("\t\t\t\t\txmlhttp=new XMLHttpRequest();\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\txmlhttp=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\txmlhttp.open(\"GET\",\"insertAnswerCourseComment?courseId=\"+courseId+\"&content=\"+content+\"&courseCommentId=\"+courseCommentId,true);\r\n");
      out.write("\t\t\t\txmlhttp.send();\r\n");
      out.write("\t\t\t\txmlhttp.onreadystatechange=function(){\r\n");
      out.write("\t\t\t\t\tif(xmlhttp.readyState==4 && xmlhttp.status==200){\r\n");
      out.write("\t\t\t\t\t\tvar res=xmlhttp.responseText;\r\n");
      out.write("\t\t\t\t\t\tif(res==\"ok\"){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"您的评论发表成功,请去查看回复进行查看！\");\r\n");
      out.write("\t\t\t\t\t\t}else if(res==\"false\"){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"您的评论发表失败!\");\r\n");
      out.write("\t\t\t\t\t\t}else if(res=\"emailempty\"){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"请您先登录，然后在回复其他人的评论\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tallcontent[i].value='';\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function checklogin(emai){\r\n");
      out.write("\tif(emai==''){\r\n");
      out.write("\t\talert(\"请您先进行登录,如果没有登录将不能发表评论！\")\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function stare(stare,starf,courseId){\r\n");
      out.write("\tvar xmlhttp;\r\n");
      out.write("\tif(window.XMLHttpRequest){\r\n");
      out.write("\t\txmlhttp=new XMLHttpRequest();\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\txmlhttp=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t}\r\n");
      out.write("\txmlhttp.open(\"GET\",\"insertdetailCollection?courseId=\"+courseId,true);\r\n");
      out.write("\txmlhttp.send();\r\n");
      out.write("\txmlhttp.onreadystatechange=function(){\r\n");
      out.write("\t\tif(xmlhttp.readyState==4 && xmlhttp.status==200){\r\n");
      out.write("\t\t\tvar res=xmlhttp.responseText;\r\n");
      out.write("\t\t\tif(res==\"ok\"){\r\n");
      out.write("\t\t\t\tstare.style.display = \"none\";\r\n");
      out.write("\t\t\t\tstarf.style.display = \"block\";\r\n");
      out.write("\t\t\t\talert(\"您以收藏成功！\");\r\n");
      out.write("\t\t\t}else if(res==\"false\"){\r\n");
      out.write("\t\t\t\talert(\"您收藏失败!\");\r\n");
      out.write("\t\t\t}else if(res==\"emailempty\"){\r\n");
      out.write("\t\t\t\talert(\"请您先进行登录，如果没有登录不能收藏此课程\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function starf(stare,starf,courseId){\t\r\n");
      out.write("\tvar xmlhttp;\r\n");
      out.write("\tif(window.XMLHttpRequest){\r\n");
      out.write("\t\txmlhttp=new XMLHttpRequest();\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\txmlhttp=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t}\r\n");
      out.write("\txmlhttp.open(\"GET\",\"canceldetailCollection?courseId=\"+courseId,true);\r\n");
      out.write("\txmlhttp.send();\r\n");
      out.write("\txmlhttp.onreadystatechange=function(){\r\n");
      out.write("\t\tif(xmlhttp.readyState==4 && xmlhttp.status==200){\r\n");
      out.write("\t\t\tvar res=xmlhttp.responseText;\r\n");
      out.write("\t\t\tif(res==\"ok\"){\r\n");
      out.write("\t\t\t\tstarf.style.display = \"none\";\r\n");
      out.write("\t\t\t\tstare.style.display = \"block\";\r\n");
      out.write("\t\t\t\talert(\"您以取消收藏！\");\r\n");
      out.write("\t\t\t}else if(res==\"false\"){\r\n");
      out.write("\t\t\t\talert(\"您取消收藏失败!\");\r\n");
      out.write("\t\t\t}else if(res==\"emailempty\"){\r\n");
      out.write("\t\t\t\talert(\"请您先进行登录，如果没有登录不能收藏此课程\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("\tfont: 12px/1.5 Arial;\r\n");
      out.write("}\r\n");
      out.write("/* star */\r\n");
      out.write("#star {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\tmargin: 20px auto;\r\n");
      out.write("\theight: 24px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#star ul, #star span {\r\n");
      out.write("\theight: 5px;\r\n");
      out.write("\tline-height: 19px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#star ul {\r\n");
      out.write("\tmargin: 15px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#star li {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 24px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\ttext-indent: -9999px;\r\n");
      out.write("\tbackground: url(img/star.png) no-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#star strong {\r\n");
      out.write("\tcolor: #f60;\r\n");
      out.write("\tpadding-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#star li.on {\r\n");
      out.write("\tbackground-position: 0 -28px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#star p {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50px;\r\n");
      out.write("\twidth: 159px;\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tbackground: url(img/icon.gif) no-repeat;\r\n");
      out.write("\tpadding: 7px 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#star p em {\r\n");
      out.write("\tcolor: #f60;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tfont-style: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#title {\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tcolor: #03a57cd9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#title1 {\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\tcolor: #03a57cd9;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("window.onload = function (){\r\n");
      out.write("\tvar temp = $('#grade').val();\r\n");
      out.write("\t\r\n");
      out.write("\tvar oStar = document.getElementById(\"star\");\r\n");
      out.write("\tvar aLi = oStar.getElementsByTagName(\"li\");\r\n");
      out.write("\tvar oUl = oStar.getElementsByTagName(\"ul\")[0];\r\n");
      out.write("\tvar oSpan = oStar.getElementsByTagName(\"span\")[1];\r\n");
      out.write("\tvar oP = oStar.getElementsByTagName(\"p\")[0];\r\n");
      out.write("\tvar i = iScore = iStar = 0;\r\n");
      out.write("\tvar aMsg = [\r\n");
      out.write("\t\t\t\t\"很不满意|差得太离谱，与课程描述严重不符\",\r\n");
      out.write("\t\t\t\t\"不满意|部分讲解不清楚，与课程描述的不符\",\r\n");
      out.write("\t\t\t\t\"一般|讲解一般，没有课程描述的那么好\",\r\n");
      out.write("\t\t\t\t\"满意|讲解不错，与课程描述的基本一致\",\r\n");
      out.write("\t\t\t\t\"非常满意|讲课质量非常好，与课程描述的完全一致\"\r\n");
      out.write("\t\t\t\t]\r\n");
      out.write("\t\r\n");
      out.write("\tfor (i = 1; i <= aLi.length; i++){\r\n");
      out.write("\t\taLi[i - 1].index = i;\r\n");
      out.write("\t\t//鼠标移过显示分数\r\n");
      out.write("\t\taLi[i - 1].onmouseover = function (){\r\n");
      out.write("\t\t\tfnPoint(this.index);\r\n");
      out.write("\t\t\t//浮动层显示\r\n");
      out.write("\t\t\toP.style.display = \"block\";\r\n");
      out.write("\t\t\t//计算浮动层位置\r\n");
      out.write("\t\t\toP.style.left = oUl.offsetLeft + this.index * this.offsetWidth - 104 + \"px\";\r\n");
      out.write("\t\t\t//匹配浮动层文字内容\r\n");
      out.write("\t\t\toP.innerHTML = \"<em><b>\" + this.index + \"</b> 分 \" + aMsg[this.index - 1].match(/(.+)\\|/)[1] + \"</em>\" + aMsg[this.index - 1].match(/\\|(.+)/)[1]\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\taLi[i - 1].onmouseout = function(){\r\n");
      out.write("\t\t\tfor (j = 0; j < aLi.length; j++) {\r\n");
      out.write("\t\t\t\taLi[j].className = \"\";\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\toP.style.display = \"none\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//如果评过分显示评分结果,并且取消移动效果\r\n");
      out.write("\t\tif(temp!=0&&temp!=11){\r\n");
      out.write("\t\t\taLi[i-1].onmouseover=null;\r\n");
      out.write("\t\t\taLi[i-1].className = (i-1) < temp ? \"on\" : \"\";\r\n");
      out.write("\t\t\toSpan.innerHTML = \"<br/><strong>\" + (temp) + \" 分</strong>(\" + aMsg[temp - 1].match(/\\|(.+)/)[1] + \")\"\r\n");
      out.write("\t\t\taLi[i-1].onmouseout=null;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//点击后进行评分处理\r\n");
      out.write("\t\taLi[i - 1].onclick = function (){\r\n");
      out.write("\t\t\tvar joinflag = $('#joinflag').val();\r\n");
      out.write("\t\t\tvar temp1 = $('#grade').val();\r\n");
      out.write("\t\t\toSpan.style.display = \"block\";\r\n");
      out.write("\t\t\tiStar = this.index;\r\n");
      out.write("\t\t\toP.style.display = \"none\";\r\n");
      out.write("\t\t\t//如果没有登录\r\n");
      out.write("\t\t\tif(temp1==11){\r\n");
      out.write("\t\t\t\talert(\"请登录后再评分\");\r\n");
      out.write("\t\t\t\tfor (j = 0; j < aLi.length; j++) \r\n");
      out.write("\t\t\t\t\taLi[j].className = \"\";\t\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tif(joinflag==0){\r\n");
      out.write("\t\t\t\t\talert(\"请先加入课程再评分\");\r\n");
      out.write("\t\t\t\t\tfor (j = 0; j < aLi.length; j++) \r\n");
      out.write("\t\t\t\t\t\taLi[j].className = \"\";\t\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t//如果评过分点击\r\n");
      out.write("\t\t\t\t\tif(temp1!=0&&temp1!=11){\r\n");
      out.write("\t\t\t\t\t\talert(\"不能重复评分\");\r\n");
      out.write("\t\t\t\t\t\toSpan.innerHTML = \"<br/><strong>\" + (temp1) + \" 分</strong>(\" + aMsg[temp1 - 1].match(/\\|(.+)/)[1] + \")\"\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t//如果没有评过分时点击\r\n");
      out.write("\t\t\t\t\tif(temp1==0){\r\n");
      out.write("\t\t\t\t\t\tvar courseId = $('#courseId').val(); \r\n");
      out.write("\t\t\t\t\t\tvar grade = this.index;\r\n");
      out.write("\t\t\t\t\t\tvar con = confirm(\"一个课程只能评分一次，确认评分\");\r\n");
      out.write("\t\t\t\t\t\tif(con==true){\r\n");
      out.write("\t\t\t\t\t\t\tfor (j = 1; j <= aLi.length; j++){\r\n");
      out.write("\t\t\t\t\t\t\t\taLi[j - 1].onmouseout=null;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\turl:'makeScore',\r\n");
      out.write("\t\t\t\t\t\t\t\tdata:{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t'courseId':courseId,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t'grade':grade\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\ttype:'post',\r\n");
      out.write("\t\t\t\t\t\t\t\tasyn:false,\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.getElementById(\"grade\").value = result;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfor (j = 1; j <= aLi.length; j++){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\taLi[j - 1].onmouseover=null;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\toSpan.style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\toSpan.innerHTML = \"<br/><strong>\" + (result) + \" 分</strong>(\" + aMsg[result - 1].match(/\\|(.+)/)[1] + \")\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\twindow.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/courseDetail?courseId='+courseId;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t})\t\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tfor (j = 0; j < aLi.length; j++) \r\n");
      out.write("\t\t\t\t\t\t\t\taLi[j].className = \"\";\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t//评分处理\r\n");
      out.write("\tfunction fnPoint(iArg){\r\n");
      out.write("\t\t//分数赋值\r\n");
      out.write("\t\tiScore = iArg || iStar;\r\n");
      out.write("\t\tfor (i = 0; i < aLi.length; i++) aLi[i].className = i < iScore ? \"on\" : \"\";\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("};\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction pleaseLogin() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/pleaseLogin',\r\n");
      out.write("\t\t\t\t\ttype : 'post',\r\n");
      out.write("\t\t\t\t\tasyn : false,\r\n");
      out.write("\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\tif (result == \"fail\") {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"请登录再查看\");\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"personCenter\").href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/left';\r\n");
      out.write("\t\t\t\t\t\t\twindow.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/left';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-default navbar-fixed-top header\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#header-navbar-collapse\"\r\n");
      out.write("\t\t\t\taria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t<span class=\"sr-only\">e享课堂</span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\"> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/logo.png\"\r\n");
      out.write("\t\t\t\twidth=\"90px\" height=\"50px\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"header-navbar-collapse\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/courseListAll\">课程</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"#\" onclick=\"pleaseLogin()\" id=\"personCenter\">个人中心</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/demand\">需求热搜</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/aboutus.jsp\">关于我们</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container layout layout-margin-top\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-9 layout-body\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"content course-infobox\">\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix course-infobox-header\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"pull-left course-infobox-title\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pull-right course-infobox-follow\">\r\n");
      out.write("\t\t\t\t\t\t\t<span>收藏</span>&nbsp;&nbsp; <a> ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write(' ');
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix course-infobox-body\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"sidebox1 mooc-teacher\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"sidebox-body mooc-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/user/20406\" target=\"_blank\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.photo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"mooc-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t综合评分：<strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.grade}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 学习人数：<strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studypeople }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t课程价格：<strong>￥");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong><input type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"fl\" class=\"input8\" value=\"加入课程\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonclick=\"javascript:isJoin('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uemail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('\'');
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uploaduser}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"mooc-extra-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"word long-paragraph\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>课程简介：</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.courseInfo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li role=\"presentation\"><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"courseDetail?courseId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">课程章节</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li role=\"presentation\"><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"coursecomment?courseId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">课程评论</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<div class=\"tab-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane active\" id=\"labs\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"getjoin\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isj}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"getEmail\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uemail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"getcourseId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"commentAll1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--评论区域 begin-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"reviewArea clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea class=\"content comment-input\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"Please enter a comment&hellip;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonkeyup=\"keyUP(this)\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"plBtn\">评论</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--评论区域 end-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--回复区域 begin-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"comment-show\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.nickName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--回复区域 end-->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"pagination-container pagemiddle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"wordstyle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"coursecomment?courseId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&pageNum=1\"> 首页 </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp; <a class=\"wordstyle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"coursecomment?courseId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&pageNum=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageCommentList.prePageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t上一页 </a>&nbsp;&nbsp;&nbsp; <a class=\"wordstyle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"coursecomment?courseId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&pageNum=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageCommentList.nextPageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t下一页 </a>&nbsp;&nbsp;&nbsp; <a class=\"wordstyle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"coursecomment?courseId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&pageNum=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageCommentList.totalPageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t末页 </a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!--textarea高度自适应-->\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    $(function () {\r\n");
      out.write("\t\t\t\t\t\t\t\t        $('.content').flexText();\r\n");
      out.write("\t\t\t\t\t\t\t\t    });\r\n");
      out.write("\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t<!--textarea限制字数-->\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    function keyUP(t){\r\n");
      out.write("\t\t\t\t\t\t\t\t        var len = $(t).val().length;\r\n");
      out.write("\t\t\t\t\t\t\t\t        if(len > 139){\r\n");
      out.write("\t\t\t\t\t\t\t\t            $(t).val($(t).val().substring(0,140));\r\n");
      out.write("\t\t\t\t\t\t\t\t        }\r\n");
      out.write("\t\t\t\t\t\t\t\t    }\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t<!--点击评论创建评论条-->\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t    $('.commentAll1').on('click','.plBtn',function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t    \tvar photo;\r\n");
      out.write("\t\t\t\t\t\t\t\t    \tvar name;\r\n");
      out.write("\t\t\t\t\t\t\t\t    \tvar courseCommentId;\r\n");
      out.write("\t\t\t\t\t\t\t\t    \tvar commentTime;\r\n");
      out.write("\t\t\t\t\t\t\t\t    \tvar state;\r\n");
      out.write("\t\t\t\t\t\t\t\t    \tvar oHtml;\r\n");
      out.write("\t\t\t\t\t\t\t\t    \tvar courseId=document.getElementById(\"getcourseId\").value;\r\n");
      out.write("\t\t\t\t\t\t\t\t    \tvar uemail = document.getElementById(\"getEmail\").value;\r\n");
      out.write("\t\t\t\t\t\t\t\t        var myDate = new Date();\r\n");
      out.write("\t\t\t\t\t\t\t\t        //获取当前年\r\n");
      out.write("\t\t\t\t\t\t\t\t        var year=myDate.getFullYear();\r\n");
      out.write("\t\t\t\t\t\t\t\t        //获取当前月\r\n");
      out.write("\t\t\t\t\t\t\t\t        var month=myDate.getMonth()+1;\r\n");
      out.write("\t\t\t\t\t\t\t\t        //获取当前日\r\n");
      out.write("\t\t\t\t\t\t\t\t        var date=myDate.getDate();\r\n");
      out.write("\t\t\t\t\t\t\t\t        var h=myDate.getHours();       //获取当前小时数(0-23)\r\n");
      out.write("\t\t\t\t\t\t\t\t        var m=myDate.getMinutes();     //获取当前分钟数(0-59)\r\n");
      out.write("\t\t\t\t\t\t\t\t        if(m<10) m = '0' + m;\r\n");
      out.write("\t\t\t\t\t\t\t\t        var s=myDate.getSeconds();\r\n");
      out.write("\t\t\t\t\t\t\t\t        if(s<10) s = '0' + s;\r\n");
      out.write("\t\t\t\t\t\t\t\t        var now=year+'-'+month+\"-\"+date+\" \"+h+':'+m+\":\"+s;\r\n");
      out.write("\t\t\t\t\t\t\t\t        //获取输入内容\r\n");
      out.write("\t\t\t\t\t\t\t\t        var oSize = $(this).parents('.reviewArea ').find('.comment-input').val();\r\n");
      out.write("\t\t\t\t\t\t\t\t        if(uemail!=\"\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t        \tif(oSize!=\"\"){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t        $.post(\"insertCourseComment\",{'text':oSize,'courseId':courseId},function(data){\r\n");
      out.write("\t\t\t\t\t\t\t\t        \t\r\n");
      out.write("\t\t\t\t\t\t\t\t        \t\tconsole.log(2)\r\n");
      out.write("\t\t\t\t\t\t\t\t        \t\tconsole.log(data)\r\n");
      out.write("\t\t\t\t\t\t\t\t        \t\tvar res = $.parseJSON(data);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \tconsole.log(res);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t$.each(res,function(i,n){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\tphoto=n[0];\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\tname=n[1];\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\tcourseCommentId=n[2];\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\tvar commentTime1=n[3];\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\tvar commentTime2=new Date(commentTime1);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\tvar year=commentTime2.getFullYear();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        //获取当前月\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        var month=commentTime2.getMonth()+1;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        //获取当前日\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        var date=commentTime2.getDate();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        var h=commentTime2.getHours();       //获取当前小时数(0-23)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        var m=commentTime2.getMinutes();     //获取当前分钟数(0-59)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        if(m<10) m = '0' + m;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        var s=commentTime2.getSeconds();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        if(s<10) s = '0' + s;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        commentTime=year+'-'+month+\"-\"+date+\" \"+h+':'+m+\":\"+s;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        state=parseInt(n[4]);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        console.log(state);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\t/* var RexStr = /\\<|\\>/g;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\toSize = oSize.replace(RexStr, function(MatchStr) {  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\t      switch (MatchStr) {  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\t      case \"<\":  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\t        return \"< \";  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\t        break;  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\t      case \">\":  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\t        return \" >\";  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\t        break;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\t      default:  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\t        break;  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\t      }  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\t    });*/\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\tif(state==1){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\t\talert(\"您的评论以发表成功！\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t        \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t        //动态创建评论模块\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t        oHtml = '<div class=\"comment-show-con clearfix\" value=\"'+courseCommentId+'\" id=\"'+courseCommentId+'\"><div class=\"comment-show-con-img pull-left\"><img src=\"'+photo+'\" alt=\"user photo\" style=\"width:50px;height:50px;\"></div> <div class=\"comment-show-con-list1 pull-left clearfix\">'+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t        '<div class=\"pl-text clearfix\"><a href=\"#\" class=\"comment-size-name1\">'+name+': </a> <span class=\"my-pl-con1\" value=\"'+courseCommentId+'\">&nbsp;'+oSize+'</span></div> <div class=\"date-dz\">'+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t        '<span class=\"date-dz-left pull-left comment-time\">'+commentTime+'</span><div class=\"date-dz-right pull-right comment-pl-block\">'+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t        ' <a href=\"javascript:;\" class=\"date-dz-pl pl-hf hf-con-block pull-left\">回复</a> <span class=\"pull-left date-dz-line\">|</span><a href=\"javascript:;\" class=\"date-dz-z pull-left hf-con-block-can\"><i class=\"date-dz-z-click-red\"></i>查看回复</a></div> </div><div class=\"hf-list-con\"></div></div></div>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t        \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t        console.log(oHtml);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t        if(oSize.replace(/(^\\s*)|(\\s*$)/g, \"\") != ''){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t            $('.plBtn').parents('.reviewArea ').siblings('.comment-show').prepend(oHtml);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t            $('.plBtn').parents('.reviewArea ').find('.comment-input').prop('value','').siblings('pre').find('span').text('');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t        }\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\t}else if(state==0){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\t\talert(\"请加入课程后在发表评论！\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\t\t if(oSize.replace(/(^\\s*)|(\\s*$)/g, \"\") != ''){    \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t            $('.plBtn').parents('.reviewArea ').find('.comment-input').prop('value','').siblings('pre').find('span').text('');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t       }\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t});\r\n");
      out.write("\t\t\t\t\t\t\t\t        });\r\n");
      out.write("\t\t\t\t\t\t\t\t        \t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \talert(\"评论的内容不能为空！\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        }}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        \talert(\"请您登录后在发表评论！\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        }\r\n");
      out.write("\t\t\t\t\t\t\t\t    });\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t<!--点击回复动态创建回复块-->\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    $('.comment-show').on('click','.pl-hf',function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t        //获取回复人的名字\r\n");
      out.write("\t\t\t\t\t\t\t\t        var fhName = $(this).parents('.date-dz-right').parents('.date-dz').siblings('.pl-text').find('.comment-size-name1').html();\r\n");
      out.write("\t\t\t\t\t\t\t\t        //回复@\r\n");
      out.write("\t\t\t\t\t\t\t\t        var fhN = '回复@'+fhName;\r\n");
      out.write("\t\t\t\t\t\t\t\t        //var oInput = $(this).parents('.date-dz-right').parents('.date-dz').siblings('.hf-con');\r\n");
      out.write("\t\t\t\t\t\t\t\t        var fhHtml = '<div class=\"hf-con pull-left\"> <textarea class=\"content comment-input hf-input\" placeholder=\"\" onkeyup=\"keyUP(this)\"></textarea> <a href=\"javascript:;\" class=\"hf-pl\">评论</a></div>';\r\n");
      out.write("\t\t\t\t\t\t\t\t        //显示回复\r\n");
      out.write("\t\t\t\t\t\t\t\t        if($(this).is('.hf-con-block')){\r\n");
      out.write("\t\t\t\t\t\t\t\t            $(this).parents('.date-dz-right').parents('.date-dz').append(fhHtml);\r\n");
      out.write("\t\t\t\t\t\t\t\t            $(this).removeClass('hf-con-block');\r\n");
      out.write("\t\t\t\t\t\t\t\t            //$('.content').flexText();\r\n");
      out.write("\t\t\t\t\t\t\t\t            $(this).parents('.date-dz-right').siblings('.hf-con').find('.pre').css('padding','6px 15px');\r\n");
      out.write("\t\t\t\t\t\t\t\t            //console.log($(this).parents('.date-dz-right').siblings('.hf-con').find('.pre'))\r\n");
      out.write("\t\t\t\t\t\t\t\t            //input框自动聚焦\r\n");
      out.write("\t\t\t\t\t\t\t\t            //$(this).parents('.date-dz-right').siblings('.hf-con').find('.hf-input').val('').focus().val(fhN);\r\n");
      out.write("\t\t\t\t\t\t\t\t        }else {\r\n");
      out.write("\t\t\t\t\t\t\t\t            $(this).addClass('hf-con-block');\r\n");
      out.write("\t\t\t\t\t\t\t\t            $(this).parents('.date-dz-right').siblings('.hf-con').remove();\r\n");
      out.write("\t\t\t\t\t\t\t\t        }\r\n");
      out.write("\t\t\t\t\t\t\t\t    });\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t<!--评论回复块创建-->\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    $('.comment-show').on('click','.hf-pl',function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t    \t var courseId=document.getElementById(\"getcourseId\").value;\r\n");
      out.write("\t\t\t\t\t\t\t\t    \t var oThis = $(this);\r\n");
      out.write("\t\t\t\t\t\t\t\t    \t var myDate = new Date();\r\n");
      out.write("\t\t\t\t\t\t\t\t        //获取当前年\r\n");
      out.write("\t\t\t\t\t\t\t\t        var year=myDate.getFullYear();\r\n");
      out.write("\t\t\t\t\t\t\t\t        //获取当前月\r\n");
      out.write("\t\t\t\t\t\t\t\t        var month=myDate.getMonth()+1;\r\n");
      out.write("\t\t\t\t\t\t\t\t        //获取当前日\r\n");
      out.write("\t\t\t\t\t\t\t\t        var date=myDate.getDate();\r\n");
      out.write("\t\t\t\t\t\t\t\t        var h=myDate.getHours();       //获取当前小时数(0-23)\r\n");
      out.write("\t\t\t\t\t\t\t\t        var m=myDate.getMinutes();     //获取当前分钟数(0-59)\r\n");
      out.write("\t\t\t\t\t\t\t\t        if(m<10) m = '0' + m;\r\n");
      out.write("\t\t\t\t\t\t\t\t        var s=myDate.getSeconds();\r\n");
      out.write("\t\t\t\t\t\t\t\t        if(s<10) s = '0' + s;\r\n");
      out.write("\t\t\t\t\t\t\t\t        var now=year+'-'+month+\"-\"+date+\" \"+h+':'+m+\":\"+s;\r\n");
      out.write("\t\t\t\t\t\t\t\t        var oAt ='';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t     var th=$(this).parents('.hf-con').parents('.all-pl-con').css('display','block')\r\n");
      out.write("\t\t\t\t\t\t\t\t        //获取输入内容\r\n");
      out.write("\t\t\t\t\t\t\t\t        var oHfVal = $(this).parents('.hf-con').find('.hf-input').val();\r\n");
      out.write("\t\t\t\t\t\t\t\t        var oHfTop =$(this).parents('.hf-con').parents('.comment-show-con').attr(\"value\");\r\n");
      out.write("\t\t\t\t\t\t\t\t        console.log(\"sssssssss\")\r\n");
      out.write("\t\t\t\t\t\t\t\t        console.log(oHfVal)\r\n");
      out.write("\t\t\t\t\t\t\t\t        console.log(\"sssssssss\")\r\n");
      out.write("\t\t\t\t\t\t\t\t        var oHfName = $(this).parents('.hf-con').parents('.date-dz').siblings('.pl-text').find('.comment-size-name').html();\r\n");
      out.write("\t\t\t\t\t\t\t\t        var oHfId = $(this).parents('.hf-con').parents('.date-dz').siblings('.pl-text').find('.my-pl-con1').attr(\"value\");\r\n");
      out.write("\t\t\t\t\t\t\t\t        var username=$(this).parents('.hf-con').parents('.date-dz').parents('.comment-show').attr(\"value\");\r\n");
      out.write("\t\t\t\t\t\t\t\t        console.log(oHfId)\r\n");
      out.write("\t\t\t\t\t\t\t\t        console.log(username)\r\n");
      out.write("\t\t\t\t\t\t\t\t        var oAllVal = '回复@'+oHfName;\r\n");
      out.write("\t\t\t\t\t\t\t\t        if(now == ''){\r\n");
      out.write("\t\t\t\t\t                        oAt = res.hfContent;\r\n");
      out.write("\t\t\t\t\t                    }else {\r\n");
      out.write("\t\t\t\t\t                        oAt = '回复<a href=\"#\" class=\"atName\" >@'+oHfName+'</a> '+oHfVal;\r\n");
      out.write("\t\t\t\t\t                    }\r\n");
      out.write("\t\t\t\t\t\t\t\t        // || oHfVal == oAllVal\r\n");
      out.write("\t\t\t\t\t\t\t\t        if(oHfVal.replace(/^ +| +$/g,'') == '' ){\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t        }else {\r\n");
      out.write("\t\t\t\t\t\t\t\t            $.post(\"insertAnswerCourseComment\",{'text':oHfVal,'commentPid':oHfId,'courseId':courseId,oHfTop:oHfTop},function(result){\r\n");
      out.write("\t\t\t\t\t\t\t\t            \tif(result==\"emailempty\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t            \t\talert(\"请您登陆后在回复评论！\");\r\n");
      out.write("\t\t\t\t\t\t\t\t            \t}else if(result=\"ok\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t            \t\tif($(\"#\"+oHfTop+\"\").find('.comment-show-con-list').find('.date-dz-z').is('.hf-con-block-can')){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            \tconsole.log(1547)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            }else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            \tconsole.log(2222)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                var oHtml = '<div class=\"all-pl-con\"><div class=\"pl-text hfpl-text clearfix\"><a href=\"#\" class=\"comment-size-name\">'+username+':</a><span class=\"my-pl-con\" value=\"\">'+oAt+'</span></div><div class=\"date-dz\"> <span class=\"date-dz-left pull-left comment-time\">'+now+'</span> <div class=\"date-dz-right pull-right comment-pl-block\"> <a href=\"javascript:;\" class=\"date-dz-pl pl-hf hf-con-block pull-left\">回复</a></div> </div></div>';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                th.after(oHtml) && $(\"#\"+oHfTop+\"\").find('.pl-hf').addClass('hf-con-block');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t            }\r\n");
      out.write("\t\t\t\t\t\t\t\t            \t\talert(\"您的评论发表成功！\");\r\n");
      out.write("\t\t\t\t\t\t\t\t            \t}else if(result==\"false\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t            \t\talert(\"您的评论发表失败，请重新发送！\");\r\n");
      out.write("\t\t\t\t\t\t\t\t            \t}\r\n");
      out.write("\t\t\t\t\t\t\t\t            \t\r\n");
      out.write("\t\t\t\t\t\t\t\t                });\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\toThis.parents('.hf-con').remove();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t            //});\r\n");
      out.write("\t\t\t\t\t\t\t\t        }\r\n");
      out.write("\t\t\t\t\t\t\t\t    });\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t<!--查看回复-->\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('.comment-show').on('click','.date-dz-z',function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif($(this).is('.hf-con-block-can')){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        var oHfName = $(this).parents('.hf-con').parents('.date-dz').siblings('.pl-text').find('.comment-size-name').html();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        var oHfId = $(this).parents('.hf-con').parents('.date-dz').siblings('.pl-text').find('.my-pl-con').attr(\"value\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        var oHfTop =$(this).parents('.comment-show-con').attr(\"value\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        console.log(oHfId)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        console.log(oHfTop)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        var oAllVal = '回复@'+oHfName;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        $(this).removeClass('hf-con-block-can');\r\n");
      out.write("\t\t\t\t\t\t\t\t            $.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/findsoncomment\",{oHfTop:oHfTop},function(data){\r\n");
      out.write("\t\t\t\t\t\t\t\t            \tvar res = $.parseJSON(data);\r\n");
      out.write("\t\t\t\t\t\t\t\t                var oAt = '';\r\n");
      out.write("\t\t\t\t\t\t\t\t                var oHf = '';\r\n");
      out.write("\t\t\t\t\t\t\t\t                var id;\r\n");
      out.write("\t\t\t\t\t\t\t\t                $.each(res,function(n,v){\r\n");
      out.write("\t\t\t\t\t\t\t\t                \tconsole.log(res)\r\n");
      out.write("\t\t\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t\t                    var arr;\r\n");
      out.write("\t\t\t\t\t\t\t\t                    var ohfNameArr;\r\n");
      out.write("\t\t\t\t\t\t\t\t                    var myDate = new Date(v[1]);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        //获取当前年\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        var year=myDate.getFullYear();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        //获取当前月\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        var month=myDate.getMonth()+1;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        //获取当前日\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        var date=myDate.getDate();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        var h=myDate.getHours();       //获取当前小时数(0-23)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        var m=myDate.getMinutes();     //获取当前分钟数(0-59)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        if(m<10) m = '0' + m;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        var s=myDate.getSeconds();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        if(s<10) s = '0' + s;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        var now=year+'-'+month+\"-\"+date+\" \"+h+':'+m+\":\"+s;\r\n");
      out.write("\t\t\t\t\t\t\t\t                    if(v[1] == ''){\r\n");
      out.write("\t\t\t\t\t\t\t\t                        oAt = res.hfContent;\r\n");
      out.write("\t\t\t\t\t\t\t\t                    }else {\r\n");
      out.write("\t\t\t\t\t\t\t\t                        oAt = '回复<a href=\"#\" class=\"atName\" >@'+v[3]+'</a>  '+v[2];\r\n");
      out.write("\t\t\t\t\t\t\t\t                    }\r\n");
      out.write("\t\t\t\t\t\t\t\t                    oHf = oHfName;\r\n");
      out.write("\t\t\t\t\t\t\t\t                \r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t                var oHtml = '<div class=\"all-pl-con\"><div class=\"pl-text hfpl-text clearfix\"><a href=\"#\" class=\"comment-size-name\">'+v[4]+' : </a><span class=\"my-pl-con1\" value=\"'+v[0] +'\">'+oAt+'</span></div><div class=\"date-dz\"> <span class=\"date-dz-left pull-left comment-time\">'+now+'</span> <div class=\"date-dz-right pull-right comment-pl-block\"> <a href=\"javascript:;\" class=\"date-dz-pl pl-hf hf-con-block pull-left\">回复</a></div> </div></div>';\r\n");
      out.write("\t\t\t\t\t\t\t\t                \r\n");
      out.write("\t\t\t\t\t\t\t\t                $(\"#\"+oHfTop+\"\").find('.hf-list-con').css('display','block').prepend(oHtml) && $(\"#\"+oHfTop+\"\").find('.pl-hf').addClass('hf-con-block');\r\n");
      out.write("\t\t\t\t\t\t\t\t                });\r\n");
      out.write("\t\t\t\t\t\t\t\t            });\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\t\t\t\t            $(this).addClass('hf-con-block-can');\r\n");
      out.write("\t\t\t\t\t\t\t\t            $(this).parents('.date-dz').siblings('.hf-list-con').find('.all-pl-con').remove();\r\n");
      out.write("\t\t\t\t\t\t\t\t        }\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3 layout-side\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"side-image-pc\">\r\n");
      out.write("\t\t\t\t\t<div id=\"star\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"title\">给课程打个分吧！</span>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"javascript:;\">1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"javascript:;\">2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"javascript:;\">3</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"javascript:;\">4</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"javascript:;\">5</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<span id=\"title1\"></span> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      out.print(request.getParameter("courseId"));
      out.write("\" id=\"courseId\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"courseId\" /> <input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myGrade}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"grade\" name=\"grade\" /> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${joinflag}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"joinflag\" name=\"joinflag\" />\r\n");
      out.write("\t\t\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"sidebox mooc-teacher\" style=\"margin-top: 100px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"sidebox-header mooc-header\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"sidebox-title\">课程教师</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"sidebox-body mooc-content\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"information.jsp\" target=\"_blank\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"img/Linux&c.png\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mooc-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uploadCourseUser.nickName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"courses\">\r\n");
      out.write("\t\t\t\t\t\t\t\t共发布过<strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uploadCourseCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>门课程\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mooc-extra-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"word long-paragraph\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uploadCourseUser.introduction}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"sidebox-footer mooc-footer\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"information.jsp\" target=\"_blank\">查看老师的所有课程 ></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 此处展示老师的另外一些课程 -->\r\n");
      out.write("\t\t\t\t<div class=\"wordstyle\">\r\n");
      out.write("\t\t\t\t\t<strong>类似课程</strong>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-xs-6 col-sm-3 col-md-8 footer-col footer-a\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.html\" target=\"_blank\"\r\n");
      out.write("\t\t\t\t\tclass=\"col-md-2  \">关于我们</a> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/privacy/index.html\"\r\n");
      out.write("\t\t\t\t\ttarget=\"_blank\" class=\"col-md-2  \">合作伙伴</a> <a\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.html\" target=\"_blank\"\r\n");
      out.write("\t\t\t\t\tclass=\"col-md-2  \">联系客服</a> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/paths/index.html\"\r\n");
      out.write("\t\t\t\t\ttarget=\"_blank\" class=\"col-md-2  \">联系我们</a> <a\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.html\" target=\"_blank\" class=\"col-md-2  \">隐私条款</a>\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.html\" target=\"_blank\"\r\n");
      out.write("\t\t\t\t\tclass=\"col-md-2  \">法律声明</a> <br> \r\n");
      out.write("\t\t\t\t<div class=\"copyright\" style=\"width: 800px;\"><span>Copyright\r\n");
      out.write("\t\t\t\t\t@3013-3016 实验楼在线教育</span> <span class=\"ver-line\"> | </span> \r\n");
      out.write("\t\t\t\t\t<span>蜀ICP备13019763号</span></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 clearfix footer-col footer-d\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-3 \">\r\n");
      out.write("\t\t\t\t\t<div class=\"social-item footer-weixin-item footer-img\"\r\n");
      out.write("\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-weixin\"></i>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-weixin\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/footer-weixin.png\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"social-item footer-qq-item  footer-img\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-qq\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"social-item footer-weibo-item  footer-img\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://weibo.com/shiyanlou3013\" target=\"_blank\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-weibo\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\tfunction textframe(btn1,btn2,textbox){\r\n");
      out.write("\t\tvar oBtn1 = btn1;\r\n");
      out.write("\t\tvar oBtn2 = btn2;\r\n");
      out.write("\t\tvar oText = textbox;\r\n");
      out.write("\t\toBtn1.onclick = function() {\r\n");
      out.write("\t\t\toText.style.display = \"block\";\r\n");
      out.write("\t\t\toBtn2.style.display = \"block\";\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /coursecomment.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /coursecomment.jsp(4,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /header.jsp(46,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginFlag=='0'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t<div class=\"navbar-right btns\" id=\"loginhidden\">\r\n");
        out.write("\t\t\t\t\t<a class=\"btn btn-default navbar-btn sign-in\" data-sign=\"signin\"\r\n");
        out.write("\t\t\t\t\t\thref=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/#sign-modal\" data-toggle=\"modal\">登录</a> <a\r\n");
        out.write("\t\t\t\t\t\tclass=\"btn btn-default navbar-btn sign-up\" data-sign=\"signup\"\r\n");
        out.write("\t\t\t\t\t\thref=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/#sign-modal\" data-toggle=\"modal\">注册</a>\r\n");
        out.write("\t\t\t\t</div>\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /header.jsp(55,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginFlag=='1'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t<div class=\"navbar-right btns\" id=\"loginshow\" style=\"float:right;\">\r\n");
        out.write("\t\t\t\t\t<img src=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write('/');
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.photo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" style=\"width: 35px; height: 35px\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/#\">\r\n");
        out.write("\t\t\t\t\t<a class=\"btn btn-default navbar-btn sign-up\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/quit\">退出</a>\r\n");
        out.write("\t\t\t\t</div>\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /coursecomment.jsp(368,39) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isCollection=='fail'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<span style=\"display: block; float: right; clear: right\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\tid=\"star1\" onclick=\"stare(star1,star2,");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write(")\">☆</span>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<span style=\"display: none; float: right; clear: right\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\tid=\"star2\" onclick=\"starf(star1,star2,");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write(")\">★</span>\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f3.setParent(null);
    // /coursecomment.jsp(374,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isCollection=='ok'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
    if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<span style=\"display: block; float: right; clear: right\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\tid=\"star3\" onclick=\"starf(star4,star3,");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write(")\">★</span>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<span style=\"display: none; float: right; clear: right\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\tid=\"star4\" onclick=\"stare(star4,star3,");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write(")\">☆</span>\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /coursecomment.jsp(436,9) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${commentList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /coursecomment.jsp(436,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("c");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"comment-show-con clearfix\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.courseCommentId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.courseCommentId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"comment-show-con-img pull-left\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('/');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.user.photo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" alt=\"user photo\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: 50px; height: 50px;\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"comment-show-con-list1 pull-left clearfix\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"pl-text clearfix\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"comment-size-name1\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.user.nickName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(":\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a> <span class=\"my-pl-con1\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.courseCommentId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">&nbsp;");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.text}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"date-dz\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"date-dz-left pull-left comment-time\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c.commentTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"date-dz-right pull-right comment-pl-block\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:;\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"date-dz-pl pl-hf hf-con-block pull-left\">回复</a> <span\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"pull-left date-dz-line\">|</span> <a\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"javascript:;\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"date-dz-z pull-left hf-con-block-can\"><i\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"date-dz-z-click-red\"></i>查看回复</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hf-list-con\"></div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /coursecomment.jsp(797,4) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mpc}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /coursecomment.jsp(797,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("lc");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<div class=\"col-md-14 col-sm-16  course\">\r\n");
          out.write("\t\t\t\t\t\t<a class=\"course-box\"\r\n");
          out.write("\t\t\t\t\t\t\thref=\"courseDetail?courseId=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lc.key.courseId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"course-img\">\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t<img alt=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lc.key.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lc.key.photo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"course-body\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<span class=\"course-title\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lc.key.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"course-footer\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<span class=\"course-per-num pull-left\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lc.value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t</a>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }
}
