/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.11
 * Generated at: 2018-12-27 14:30:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class demand_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/login.jsp", Long.valueOf(1545654998000L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1544956724000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1544330974000L));
    _jspx_dependants.put("jar:file:/D:/EShareClass/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/plailing/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1064305020000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1545913174000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>demand</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/favicon.ico\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/font-awesome//4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/highlight.js/9.8.0/monokai-sublime.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/css/libs/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/css/libs/katex/0.6.0/katex.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/css/libs/videojs/5.11.7/video-js.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/css/dest/styles.css?=2016121272249\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/jquery/2.2.4/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function addDemand(emai,pageNum,count){\r\n");
      out.write("\tvar text=document.getElementById(\"searchw\").value;\r\n");
      out.write("\tvar content='';\r\n");
      out.write("\tif(emai!=\"\"){\r\n");
      out.write("\t\tif(text!=\"\"){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:'addDemand',\r\n");
      out.write("\t\t\t\tdata:{\r\n");
      out.write("\t\t\t\t\t'search':text,\r\n");
      out.write("\t\t\t\t\t'pageNum':pageNum\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\ttype:'get',\r\n");
      out.write("\t\t\t\tasyn : false,\r\n");
      out.write("\t\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\t\tif(result=='ok'){\r\n");
      out.write("\t               \t\tdocument.getElementById(\"adddemand\").href='demand';\r\n");
      out.write("\t               \t\twindow.location.href='demand';\r\n");
      out.write("\t               \t\talert(\"您的需求已发布成功！\");\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\talert(\"您的需求发表失败！\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t            }\r\n");
      out.write(" \t\t\t });\r\n");
      out.write(" \t\t\tdocument.getElementById(\"searchw\").value=\"\";\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"需求内容不能为空！\")\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(\"请您先登录然后在发表需求！\");\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function searchWord(){\r\n");
      out.write("\tif(event.which!=16){\r\n");
      out.write("\t\t//1、获得输入框的输入的内容\r\n");
      out.write("\t\tvar word = $(\"#searchw\").val();\r\n");
      out.write("\t\tconsole.log(word+\"ccc\");\r\n");
      out.write("\t\tdocument.getElementById(\"searchMsg\").innerHTML=\"\";\r\n");
      out.write("\t\t$(\"#searchMsg\").hide();\r\n");
      out.write("\t\t//2、根据输入框的内容去数据库中模糊查询---List<Product>\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:'search',\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t\t\t\t'searchWord':word\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\ttype:'post',\r\n");
      out.write("\t\t\tasyn:false,\r\n");
      out.write("\t\t\tsuccess:function(listDemand){\r\n");
      out.write("\t\t\t\tvar msg = $.parseJSON(listDemand);\r\n");
      out.write("\t\t\t\tconsole.log(msg+\"aaa\");\r\n");
      out.write("\t\t\t\tvar res=\"\";\r\n");
      out.write("\t\t\t\tfor(var i in msg){\r\n");
      out.write("\t\t\t\t\tconsole.log(msg[i]+\"bbb\");\r\n");
      out.write("\t\t\t\t\tres=res+\"<p onmousedown='getText(div\"+i+\")' id='div\"+i+\"'>\"+msg[i]+\"</p>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(msg.length!=0){\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"searchMsg\").innerHTML=res;\r\n");
      out.write("\t\t\t\t\t$(\"#searchMsg\").show();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getText(divi){\r\n");
      out.write("\tvar text=divi.innerHTML;\r\n");
      out.write("\tdocument.getElementById(\"searchw\").value=text;\r\n");
      out.write("\t$(\"#searchMsg\").hide();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" function hidei(){\r\n");
      out.write("\t$(\"#searchMsg\").hide();\r\n");
      out.write("}  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction pleaseLogin() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/pleaseLogin',\r\n");
      out.write("\t\t\t\t\ttype : 'post',\r\n");
      out.write("\t\t\t\t\tasyn : false,\r\n");
      out.write("\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\tif (result == \"fail\") {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"请登录再查看\");\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"personCenter\").href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/left';\r\n");
      out.write("\t\t\t\t\t\t\twindow.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/left';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-default navbar-fixed-top header\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#header-navbar-collapse\"\r\n");
      out.write("\t\t\t\taria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t<span class=\"sr-only\">e享课堂</span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\"> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/logo.png\"\r\n");
      out.write("\t\t\t\twidth=\"90px\" height=\"50px\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"header-navbar-collapse\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/courseListAll\">课程</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"#\" onclick=\"pleaseLogin()\" id=\"personCenter\">个人中心</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/demand\">需求热搜</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/aboutus.jsp\">关于我们</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container layout layout-margin-top\"  style=\"width:1000px;\">\r\n");
      out.write("\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t<form AUTOCOMPLETE=\"OFF\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"demandform\" name=\"search\" id=\"searchw\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"一句话简述您的需求\" onkeyup=\"searchWord()\" onblur=\"hidei()\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" onclick=\"addDemand('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('\'');
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\" id=\"adddemand\"><input type=\"button\" class=\"btn btn-primary\" value=\"发布\"></a>\r\n");
      out.write("\t\t\t\t \t<div id=\"searchMsg\" class=\"demandform\" style=\"width:400px;height:auto;position:absolute; z-index:2;margin-top:-30px;display:none;\"></div><!-- -->\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t<div style=\"position:relative; z-index:1;\">\r\n");
      out.write("\t\t\t<ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("\t\t\t\t<li role=\"presentation\"><a href=\"#\">需求热搜</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane active\" id=\"labs\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"pagination-container pagemiddle\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"wordstyle\">共");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageDemand.totalPageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("页</span>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<a class=\"wordstyle\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/demand?pageNum=1\"> 首页 </a> &nbsp;&nbsp;&nbsp; <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"wordstyle\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/demand?pageNum=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageDemand.prePageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> 上一页 </a>&nbsp;&nbsp;&nbsp; <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"wordstyle\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/demand?pageNum=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageDemand.nextPageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> 下一页 </a>&nbsp;&nbsp;&nbsp; <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"wordstyle\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/demand?pageNum=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageDemand.totalPageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> 末页 </a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t/**\r\n");
      out.write("\t * 刷新验证码\r\n");
      out.write("\t */\r\n");
      out.write("\tfunction changeImg() {\r\n");
      out.write("\t\tvar imgSrc = $(\"#codeImg\");\r\n");
      out.write("\t\tvar src = imgSrc.attr(\"src\");\r\n");
      out.write("\t\timgSrc.attr(\"src\", chgUrl(src));\r\n");
      out.write("\t}\r\n");
      out.write("\t//加入时间戳，去缓存机制   \r\n");
      out.write("\tfunction chgUrl(url) {\r\n");
      out.write("\t\tvar timestamp = (new Date()).valueOf();\r\n");
      out.write("\t\tif ((url.indexOf(\"&\") >= 0)) {\r\n");
      out.write("\t\t\turl = url + \"&timestamp=\" + timestamp;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\turl = url + \"?timestamp=\" + timestamp;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn url;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write(" \t function checkVerify(){\r\n");
      out.write("\t\tvar email = $('#email').val();\r\n");
      out.write("\t\tvar password = $('#password').val();\r\n");
      out.write("\t\tvar captcha_v = $('#captcha_v').val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:'verify',\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t\t\t\t'email':email,\r\n");
      out.write("\t\t\t\t'password':password,\r\n");
      out.write("\t\t\t\t'captcha_v':captcha_v\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\ttype:'post',\r\n");
      out.write("\t\t\tasyn:false,\r\n");
      out.write("\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\tconsole.log(134);\r\n");
      out.write("\t\t\t\tif(result==\"1\"){\r\n");
      out.write("\t\t\t\t\twindow.location.href='register?email='+email+'&password='+password+'&captcha_v='+captcha_v;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}else if(result==\"2\"){\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"point\").innerHTML = \"\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}else if(result==\"3\"){\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"point\").innerHTML = \"\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t}else if(result==\"4\"){\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"point\").innerHTML = \"验证码错误\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t}else if(result==\"5\"){\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"point\").innerHTML = \"\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t}else if(result==\"6\"){\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"point\").innerHTML = \"验证码错误\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t}else if(result==\"7\"){\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"point\").innerHTML = \"验证码错误\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t}else if(result==\"8\"){\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"point\").innerHTML = \"邮箱、密码和验证码不能为空\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\t\r\n");
      out.write("\t} \r\n");
      out.write(" \t \r\n");
      out.write(" \tfunction checkVerifyE(){\r\n");
      out.write(" \t\tvar email = $('#email').val();\r\n");
      out.write(" \t\t$.ajax({\r\n");
      out.write(" \t\t\turl:'verifyEmail',\r\n");
      out.write(" \t\t\tdata:{\r\n");
      out.write(" \t\t\t\t'email':email\r\n");
      out.write(" \t\t\t},\r\n");
      out.write(" \t\t\ttype:'post',\r\n");
      out.write(" \t\t\tasyn:false,\r\n");
      out.write(" \t\t\tsuccess:function(result){\r\n");
      out.write(" \t\t\t\tif(result==\"email pass\"){\r\n");
      out.write(" \t\t\t\t\tdocument.getElementById(\"emailPoint\").innerHTML =\"\";\r\n");
      out.write(" \t\t\t\t}else if(result ==\"email exist\"){\r\n");
      out.write(" \t\t\t\t\tdocument.getElementById(\"emailPoint\").innerHTML =\"邮箱已注册\";\r\n");
      out.write(" \t\t\t\t}else if(result==\"email not pass\"){\r\n");
      out.write(" \t\t\t\t\tdocument.getElementById(\"emailPoint\").innerHTML = \"邮箱格式由字母、数字、下划线、中划线组成5-20位\";\r\n");
      out.write(" \t\t\t\t}\r\n");
      out.write(" \t\t\t}\r\n");
      out.write(" \t\t})\t\r\n");
      out.write(" \t}\r\n");
      out.write(" \t \r\n");
      out.write(" \t function checkVerifyP(){\r\n");
      out.write("\t\tvar password = $('#password').val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:'verifyPassword',\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t\t\t\t'password':password\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\ttype:'post',\r\n");
      out.write("\t\t\tasyn:false,\r\n");
      out.write("\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\tif(result==\"password pass\"){\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"passwordPoint\").innerHTML =\"\";\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"passwordPoint\").innerHTML = \"密码格式数字、字母、下划线组成6-19位\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\t\r\n");
      out.write("\t}\r\n");
      out.write(" \t \t \r\n");
      out.write(" \tfunction verifyUser(){\r\n");
      out.write(" \t\tvar lemail=$('#lemail').val();\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:'verifyUser',\r\n");
      out.write("\t\t\t\tdata:{\r\n");
      out.write("\t\t\t\t\t'email':lemail\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\ttype:'post',\r\n");
      out.write("\t\t\t\tasyn:false,\t\t\t\t\r\n");
      out.write("\t\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t \t\tif(result==\"email can use\"){\r\n");
      out.write("\t\t\t \t\t\tdocument.getElementById(\"notNull\").innerHTML =\"\";\r\n");
      out.write("\t\t\t \t\t}else if(result==\"email not exist\"){\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"notNull\").innerHTML =\"用户不存在\";\r\n");
      out.write("\t\t\t\t\t}else if(result=\"email error\"){\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"notNull\").innerHTML =\"邮箱错误\";\r\n");
      out.write("\t\t\t\t\t}\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\t\r\n");
      out.write(" \t}\r\n");
      out.write(" \t\r\n");
      out.write(" \tfunction toLogin(){\r\n");
      out.write(" \t\tvar lemail=$('#lemail').val();\r\n");
      out.write(" \t\tvar lpassword =$('#lpassword').val(); \t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:'login',\r\n");
      out.write("\t\t\t\tdata:{\r\n");
      out.write("\t\t\t\t\t'email':lemail,\r\n");
      out.write("\t\t\t\t\t'password':lpassword\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\ttype:'get',\r\n");
      out.write("\t\t\t\tasyn:false,\r\n");
      out.write("\t\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\t\tif(result==\"false\"){\r\n");
      out.write("\t\t\t\t\t    document.getElementById(\"notNull\").innerHTML =\"邮箱或密码错误\";  \r\n");
      out.write("\t\t\t\t\t}else if(result==\"true\"){\r\n");
      out.write("\t\t\t\t\t\twindow.location.href='index';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\t\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"modal fade\" id=\"sign-modal\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t<div class=\"modal-dialog modal-sm\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"close-modal\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("\t\t\t\t\t<li role=\"presentation\" class=\"active\"><a href=\"#signin-form\"\r\n");
      out.write("\t\t\t\t\t\taria-controls=\"signin-form\" role=\"tab\" data-toggle=\"tab\">登录</a></li>\r\n");
      out.write("\t\t\t\t\t<li role=\"presentation\"><a href=\"#signup-form\"\r\n");
      out.write("\t\t\t\t\t\taria-controls=\"signup-form\" role=\"tab\" data-toggle=\"tab\">注册</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane active\" id=\"signin-form\">\r\n");
      out.write("\t\t\t\t\t\t<form method=\"post\" onkeydown=\"if(event.keyCode==13) return toLogin();\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group-addon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-envelope\" style=\"margin: 0;\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"email\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"lemail\" placeholder=\"请输入邮箱\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonblur=\"verifyUser()\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group-addon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-lock\" style=\"margin: 0;\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"password\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"请输入密码\" id=\"lpassword\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div><span id=\"notNull\" style=\"color:red;font-size:12px;\"></span></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group remember-login\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"remember\" type=\"checkbox\" value=\"y\"> 下次自动登录\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"pull-right\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/forgetpwd1.jsp\">忘记密码？</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-primary\" type=\"button\" onclick=\"toLogin()\">登录</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group widget-signin\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>快速登录</span> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("//auth/qq?next=\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-qq\"></i></a> <a href=\"/auth/weibo?next=\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-weibo\"></i></a> <a href=\"/auth/weixin?next=\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-weixin\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group error-msg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"tip\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane\" id=\"signup-form\">\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<form method=\"post\" onkeydown=\"if(event.keyCode==13) return checkVerify();\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group-addon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-envelope\" style=\"margin: 0;\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"email\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"请输入邮箱\" id=\"email\" onblur=\"checkVerifyE()\">\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"emailPoint\" style=\"color:red;font-size:2px;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group-addon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-lock\" style=\"margin: 0;\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"password\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"请输入密码\" id=\"password\" onblur=\"checkVerifyP()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"passwordPoint\" style=\"color:red;font-size:2px;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"captcha_v\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"请输入验证码\" id=\"captcha_v\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img id=\"codeImg\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/captcha\" onclick=\"changeImg()\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"point\" style=\"color:red;font-size:2px;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"btn btn-primary\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"checkVerify()\" value=\"注册\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group agree-privacy\">\r\n");
      out.write("\t\t\t\t\t\t\t\t注册表示您已经同意我们的<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/privacy.jsp\" target=\"_blank\">隐私条款</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group widget-signup\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>快速注册</span> <a href=\"/auth/qq?next=\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-qq\"></i></a> <a href=\"/auth/weibo?next=\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-weibo\"></i></a> <a href=\"/auth/weixin?next=\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-weixin\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group error-msg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"alert alert-danger\" role=\"alert\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"app/dest/lib/lib.js?=2016121272249\"></script>\r\n");
      out.write("<script src=\"static/jquery/2.2.4/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"static/ace/1.2.5/ace.js\"></script>\r\n");
      out.write("<script src=\"static/aliyun/aliyun-oss-sdk-4.3.0.min.js\"></script>\r\n");
      out.write("<script src=\"static/highlight.js/9.8.0/highlight.min.js\"></script>\r\n");
      out.write("<script src=\"static/jspdf/1.2.61/jspdf.min.js\"></script>\r\n");
      out.write("<script src=\"static/plupload/2.1.9/js/plupload.full.min.js\"></script>\r\n");
      out.write("<script src=\"static/zeroclipboard/2.2.0/ZeroClipboard.min.js\"></script>\r\n");
      out.write("<script src=\"static/videojs/video.min.js\"></script>\r\n");
      out.write("<script src=\"static/bootstrap-tour/0.11.0/js/bootstrap-tour.min.js\"></script>\r\n");
      out.write("<script src=\"static/bootstrap-table/1.11.0/bootstrap-table.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"static/bootstrap-table/1.11.0/locale/bootstrap-table-zh-CN.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"static/bootstrap-table/1.11.0/extensions/filter-control/bootstrap-table-filter-control.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"static/ravenjs/3.7.0/raven.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\tRaven.config(\r\n");
      out.write("\t\t\t'https://bc3878b7ed0a4468a65390bd79e6e73f@sentry.shiyanlou.com/5',\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\trelease : '3.12.13'\r\n");
      out.write("\t\t\t}).install();\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"jinja-data\" data-post-url=\"\"></div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"app/dest/frontend/index.js?=2016121272249\"></script>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-xs-6 col-sm-3 col-md-8 footer-col footer-a\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.html\" target=\"_blank\"\r\n");
      out.write("\t\t\t\t\tclass=\"col-md-2  \">关于我们</a> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/privacy/index.html\"\r\n");
      out.write("\t\t\t\t\ttarget=\"_blank\" class=\"col-md-2  \">合作伙伴</a> <a\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.html\" target=\"_blank\"\r\n");
      out.write("\t\t\t\t\tclass=\"col-md-2  \">联系客服</a> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/paths/index.html\"\r\n");
      out.write("\t\t\t\t\ttarget=\"_blank\" class=\"col-md-2  \">联系我们</a> <a\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.html\" target=\"_blank\" class=\"col-md-2  \">隐私条款</a>\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.html\" target=\"_blank\"\r\n");
      out.write("\t\t\t\t\tclass=\"col-md-2  \">法律声明</a> <br> \r\n");
      out.write("\t\t\t\t<div class=\"copyright\" style=\"width: 800px;\"><span>Copyright\r\n");
      out.write("\t\t\t\t\t@3013-3016 实验楼在线教育</span> <span class=\"ver-line\"> | </span> \r\n");
      out.write("\t\t\t\t\t<span>蜀ICP备13019763号</span></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 clearfix footer-col footer-d\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-3 \">\r\n");
      out.write("\t\t\t\t\t<div class=\"social-item footer-weixin-item footer-img\"\r\n");
      out.write("\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-weixin\"></i>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-weixin\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/footer-weixin.png\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"social-item footer-qq-item  footer-img\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-qq\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"social-item footer-weibo-item  footer-img\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://weibo.com/shiyanlou3013\" target=\"_blank\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-weibo\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /demand.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /demand.jsp(4,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /header.jsp(46,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginFlag=='0'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t<div class=\"navbar-right btns\" id=\"loginhidden\">\r\n");
        out.write("\t\t\t\t\t<a class=\"btn btn-default navbar-btn sign-in\" data-sign=\"signin\"\r\n");
        out.write("\t\t\t\t\t\thref=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/#sign-modal\" data-toggle=\"modal\">登录</a> <a\r\n");
        out.write("\t\t\t\t\t\tclass=\"btn btn-default navbar-btn sign-up\" data-sign=\"signup\"\r\n");
        out.write("\t\t\t\t\t\thref=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/#sign-modal\" data-toggle=\"modal\">注册</a>\r\n");
        out.write("\t\t\t\t</div>\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /header.jsp(55,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginFlag=='1'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t<div class=\"navbar-right btns\" id=\"loginshow\" style=\"float:right;\">\r\n");
        out.write("\t\t\t\t\t<img src=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write('/');
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.photo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" style=\"width: 35px; height: 35px\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/#\">\r\n");
        out.write("\t\t\t\t\t<a class=\"btn btn-default navbar-btn sign-up\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/quit\">退出</a>\r\n");
        out.write("\t\t\t\t</div>\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /demand.jsp(122,4) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listDemand}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /demand.jsp(122,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("ld");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<div class=\"lab-item \">\r\n");
          out.write("\t\t\t\t\t\t<div>\r\n");
          out.write("\t\t\t\t\t\t\t<h4>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count=count+1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h4>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<div>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ld.text}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("\t\t\t\t\t\t<div class=\"pull-right lab-item-ctrl\">\r\n");
          out.write("\t\t\t\t\t\t\t<a class=\"btn btn-primary\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/left1\">我要开课</a>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent(null);
    // /login.jsp(209,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("ctx");
    // /login.jsp(209,6) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }
}
