/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.11
 * Generated at: 2018-12-28 00:13:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class upload2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/left.jsp", Long.valueOf(1545270560000L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1544956724000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1544330974000L));
    _jspx_dependants.put("jar:file:/D:/EShareClass/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/plailing/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1064305020000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1545913174000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>upload2</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/whir_common.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/whir_grzx.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/favicon.ico\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/font-awesome//4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/highlight.js/9.8.0/monokai-sublime.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/css/libs/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/css/libs/katex/0.6.0/katex.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/css/libs/videojs/5.11.7/video-js.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/css/dest/styles.css?=2016121272249\">\r\n");
      out.write("\r\n");
      out.write(" <style type=\"text/css\">\r\n");
      out.write("        h1 {\r\n");
      out.write("\t\t    text-align:center;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tform {\r\n");
      out.write("\t\t    width:600px;\r\n");
      out.write("\t\t    margin:auto;\r\n");
      out.write("\t\t    padding:20px 50px;\r\n");
      out.write("\t\t    border:1px solid #03a57c;\r\n");
      out.write("\t\t    border-radius:10px;\r\n");
      out.write("\t\t    display:block;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tinput {\r\n");
      out.write("\t\t    font-size:24px;\r\n");
      out.write("\t\t    margin:10px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.clear {\r\n");
      out.write("\t\t    clear:both;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.speed_box {\r\n");
      out.write("\t\t    width:600px;\r\n");
      out.write("\t\t    height:20px;\r\n");
      out.write("\t\t    display:none;\r\n");
      out.write("\t\t    border:1px solid #03a57c;\r\n");
      out.write("\t\t    border-radius:10px;\r\n");
      out.write("\t\t    overflow:hidden;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#file_box {\r\n");
      out.write("\t\t    width:100%;\r\n");
      out.write("\t\t    height:250px;\r\n");
      out.write("\t\t    border:1px solid #03a57c;\r\n");
      out.write("\t\t    border-radius:10px;\r\n");
      out.write("\t\t    display:inline-block;\r\n");
      out.write("\t\t    background:#EEE;\r\n");
      out.write("\t\t    overflow:hidden;\r\n");
      out.write("\t\t    z-index:999999;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#speed {\r\n");
      out.write("\t\t    width:0;\r\n");
      out.write("\t\t    height:100%;\r\n");
      out.write("\t\t    background:#03a57c;\r\n");
      out.write("\t\t    color:white;\r\n");
      out.write("\t\t    text-align:center;\r\n");
      out.write("\t\t    line-height:20px;\r\n");
      out.write("\t\t    font-size:16px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#file_size,#file_type,#file_time {\r\n");
      out.write("\t\t    display:inline-block;\r\n");
      out.write("\t\t    padding:5px 0px;\r\n");
      out.write("\t\t    font-size:16px;\r\n");
      out.write("\t\t    color:#03a57c;\r\n");
      out.write("\t\t    font-weight:bold;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.opts_btn {\r\n");
      out.write("\t\t    position:relative;\r\n");
      out.write("\t\t    display:inline-block;\r\n");
      out.write("\t\t    padding:8px 16px;\r\n");
      out.write("\t\t    font-size:16px;\r\n");
      out.write("\t\t    color:white;\r\n");
      out.write("\t\t    text-decoration:none;\r\n");
      out.write("\t\t    background:#03a57c;\r\n");
      out.write("\t\t    border:2px solid #03a57c;\r\n");
      out.write("\t\t    border-radius:3px;\r\n");
      out.write("\t\t    cursor:pointer;\r\n");
      out.write("\t\t    overflow:hidden;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.oFile {\r\n");
      out.write("\t\t    position:absolute;\r\n");
      out.write("\t\t    width:100%;\r\n");
      out.write("\t\t    height:100%;\r\n");
      out.write("\t\t    z-index:10;\r\n");
      out.write("\t\t    top:0px;\r\n");
      out.write("\t\t    left:0px;\r\n");
      out.write("\t\t    opacity:0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.send_btn {\r\n");
      out.write("\t\t    display:inline-block;\r\n");
      out.write("\t\t    display:none;\r\n");
      out.write("\t\t    float:right;\r\n");
      out.write("\t\t    margin-top:20px;\r\n");
      out.write("\t\t    padding:8px 16px;\r\n");
      out.write("\t\t    font-size:16px;\r\n");
      out.write("\t\t    color:white;\r\n");
      out.write("\t\t    background:#03a57c;\r\n");
      out.write("\t\t    border:1px solid transparent;\r\n");
      out.write("\t\t    border-radius:2px;\r\n");
      out.write("\t\t    cursor:pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write(" \t<script type=\"text/javascript\">\r\n");
      out.write(" \t\tvar ot;\r\n");
      out.write(" \t\tvar oloaded;\r\n");
      out.write(" \t\tvar filemaxsize = 1024*1024;\r\n");
      out.write(" \t\tvar isIE = /msie/i.test(navigator.userAgent) && !window.opera; \r\n");
      out.write("\t\t//文件选择完毕时\r\n");
      out.write("\t\tfunction FileChangeFn(event) {\r\n");
      out.write("\t\t    $('.opst_txt').text('重新选择文件');\r\n");
      out.write("\r\n");
      out.write("\t\t    var event = event || window.event,\r\n");
      out.write("\t\t        dom = '',\r\n");
      out.write("\t\t        ofile = $(\"#oFile\").get(0).files[0],\r\n");
      out.write("\t\t        otype = ofile.type || '获取失败',\r\n");
      out.write("\t\t        osize = ofile.size / 1048576,\r\n");
      out.write("\r\n");
      out.write("\t\t        filetypes =[\"video/mp4\",\"video/flv\"];\r\n");
      out.write("\t\t        ourl = window.URL.createObjectURL(ofile); //文件临时地址\r\n");
      out.write("\t\t        dom = '<video id=\"video\" width=\"100%\" height=\"100%\" controls=\"controls\" autoplay=\"autoplay\" src=' + ourl + '></video>';\r\n");
      out.write("\t        if(ofile){\r\n");
      out.write("\t            var isnext = false;\r\n");
      out.write("\t            var fileend = otype;\r\n");
      out.write("\t            if(filetypes && filetypes.length>0){\r\n");
      out.write("\t                for(var i =0; i<filetypes.length;i++){\r\n");
      out.write("\t                    if(filetypes[i]==fileend){\r\n");
      out.write("\t                        isnext = true;\r\n");
      out.write("\t                        break;\r\n");
      out.write("\t                    }\r\n");
      out.write("\t                }\r\n");
      out.write("\t            }\r\n");
      out.write("\t            if(!isnext){\r\n");
      out.write("\t                alert(\"不接受此文件类型！\");\r\n");
      out.write("\t                event.value =\"\";\r\n");
      out.write("\t                return false;\r\n");
      out.write("\t            }else{\r\n");
      out.write("\t    \t\t    $('#file_type').text(\"文件类型：\" + otype);\r\n");
      out.write("\t    \t\t    $('#file_size').text(\"文件大小:\" + osize.toFixed(2) + \"MB\");\r\n");
      out.write("\t    \t\t    $('.send_btn').show();\r\n");
      out.write("\t            }\r\n");
      out.write("\t        }\r\n");
      out.write("\t\t    console.log(\"文件类型：\" + otype); //文件类型\r\n");
      out.write("\t\t    console.log(\"文件大小：\" + osize); //文件大小\r\n");
      out.write("\t\t\tif (isIE && !event.files) {    //获取当前文件大小\r\n");
      out.write("\t\t\t\tvar filePath = event.value; \r\n");
      out.write("\t\t\t\tvar fileSystem = new ActiveXObject(\"Scripting.FileSystemObject\"); \r\n");
      out.write("\t\t\t\tif(!fileSystem.FileExists(filePath)){ \r\n");
      out.write("\t\t\t\t\talert(\"附件不存在，请重新输入！\"); \r\n");
      out.write("\t\t\t\t\treturn false; \r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t\tvar file = fileSystem.GetFile (filePath); \r\n");
      out.write("\t\t\t\tfileSize = file.Size; \r\n");
      out.write("\t\t\t} else { \r\n");
      out.write("\t\t\t\tfileSize = ofile.size; \r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t\tvar size = fileSize / 1024; \r\n");
      out.write("\t\t\tif(size>filemaxsize){ \r\n");
      out.write("\t\t\t\tdocument.getElementById(\"uploadSpan\").innerHTML = \"文件大小不能大于\"+filemaxsize/1024+\"M\"; \r\n");
      out.write("\t\t\t\tevent.value =\"\"; \r\n");
      out.write("\t\t\t\treturn false; \r\n");
      out.write("\t\t\t} else{\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"uploadSpan\").innerHTML = \"\";\r\n");
      out.write("\t\t\t    $('#file_box').html(dom);\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//侦查附件上传情况 ,这个方法大概0.05-0.1秒执行一次\r\n");
      out.write("\t\tfunction OnProgRess(event) {\r\n");
      out.write("\t\t    var event = event || window.event;\r\n");
      out.write("\t\t    //console.log(event);  //事件对象\r\n");
      out.write("\t\t    console.log(\"已经上传：\" + event.loaded); //已经上传大小情况(已上传大小，上传完毕后就 等于 附件总大小)\r\n");
      out.write("\t\t    //console.log(event.total);  //附件总大小(固定不变)\r\n");
      out.write("\t\t    var loaded = Math.floor(100 * (event.loaded / event.total)); //已经上传的百分比  \r\n");
      out.write("\t\t    $(\"#speed\").html(loaded + \"%\").css(\"width\", loaded + \"%\");\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    var time = document.getElementById(\"file_time\");\r\n");
      out.write("\t\t    var nt = new Date().getTime(); //获取当前时间\r\n");
      out.write("\t\t    var pertime = (nt - ot) / 1000; //计算出上次调用该方法时到现在的时间差，单位为s\r\n");
      out.write("\t\t    ot = new Date().getTime(); //重新赋值时间，用于下次计算\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t    var perload = event.loaded - oloaded; //计算该分段上传的文件大小，单位b \r\n");
      out.write("\t\t    oloaded = event.loaded; //重新赋值已上传文件大小，用以下次计算\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t    //上传速度计算\r\n");
      out.write("\t\t    var speed = perload / pertime; //单位b/s\r\n");
      out.write("\t\t    var bspeed = speed;\r\n");
      out.write("\t\t    var units = 'b/s'; //单位名称\r\n");
      out.write("\t\t    if(speed / 1024 > 1) {\r\n");
      out.write("\t\t        speed = speed / 1024;\r\n");
      out.write("\t\t        units = 'k/s';\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    if(speed / 1024 > 1) {\r\n");
      out.write("\t\t        speed = speed / 1024;\r\n");
      out.write("\t\t        units = 'M/s';\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    speed = speed.toFixed(1);\r\n");
      out.write("\t\t    //剩余时间\r\n");
      out.write("\t\t    var resttime = ((event.total - event.loaded) / bspeed).toFixed(1);\r\n");
      out.write("\t\t    time.innerHTML = '上传速度：' + speed + units + '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;剩余时间：' + resttime + 's';\r\n");
      out.write("\t\t    if(bspeed == 0)\r\n");
      out.write("\t\t        time.innerHTML = '上传已取消';\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//开始上传文件\r\n");
      out.write("\t\tfunction UploadFileFn(courseId) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t    $('.speed_box').show();\r\n");
      out.write("\t\t    var oFile = $(\"#oFile\").get(0).files[0]; //input file标签\r\n");
      out.write("\t\t    var catalog=$(\"#catalog\").val();\r\n");
      out.write("\t\t    if(catalog == null || catalog == \"\" || catalog == undefined){\r\n");
      out.write("\t\t    \talert(\"目录名不能为空!\");\r\n");
      out.write("\t\t    }else {\r\n");
      out.write("\t\t\t    formData = new FormData(); //创建FormData对象\r\n");
      out.write("\t\t\t    xhr = $.ajaxSettings.xhr(); //创建并返回XMLHttpRequest对象的回调函数(jQuery中$.ajax中的方法)\r\n");
      out.write("\t\t\t    formData.append(\"file\", oFile); //将上传name属性名(注意：一定要和 file元素中的name名相同)，和file元素追加到FormData对象中去\r\n");
      out.write("\t\t\t    formData.append(\"catalog\", catalog);\r\n");
      out.write("\t\t\t    formData.append(\"courseId\", courseId);\r\n");
      out.write("\t\t\t    $.ajax({\r\n");
      out.write("\t\t\t        type: \"POST\",\r\n");
      out.write("\t\t\t        url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/upload1/upload1\", // 后端服务器上传地址\r\n");
      out.write("\t\t\t        data: formData, // formData数据\r\n");
      out.write("\t\t\t        cache: false, // 是否缓存\r\n");
      out.write("\t\t\t        async: true, // 是否异步执行\r\n");
      out.write("\t\t\t        processData: false, // 是否处理发送的数据  (必须false才会避开jQuery对 formdata 的默认处理)\r\n");
      out.write("\t\t\t        contentType: false, // 是否设置Content-Type请求头\r\n");
      out.write("\t\t\t        xhr: function() {\r\n");
      out.write("\t\t\t            if (OnProgRess && xhr.upload) {\r\n");
      out.write("\t\t\t            \tot = new Date().getTime();\r\n");
      out.write("\t\t\t            \toloaded=0;\r\n");
      out.write("\t\t\t                xhr.upload.addEventListener(\"progress\", OnProgRess, false);\r\n");
      out.write("\t\t\t                return xhr;\r\n");
      out.write("\t\t\t            }\r\n");
      out.write("\t\t\t        },\r\n");
      out.write("\t\t\t        success: function(returndata) {\r\n");
      out.write("\t\t\t            $(\"#speed\").html(\"上传成功\");\r\n");
      out.write("\t\t\t            window.location.href =\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/upload3.jsp\";\r\n");
      out.write("\t\t\t            //alert(returndata);  \r\n");
      out.write("\t\t\t        },\r\n");
      out.write("\t\t\t        error: function(returndata) {\r\n");
      out.write("\t\t\t            $(\"#speed\").html(\"上传失败\");\r\n");
      out.write("\t\t\t            console.log(returndata)\r\n");
      out.write("\t\t\t            alert('请正确配置后台服务！');\r\n");
      out.write("\t\t\t        }\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t};\r\n");
      out.write("    </script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction pleaseLogin() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/pleaseLogin',\r\n");
      out.write("\t\t\t\t\ttype : 'post',\r\n");
      out.write("\t\t\t\t\tasyn : false,\r\n");
      out.write("\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\tif (result == \"fail\") {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"请登录再查看\");\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"personCenter\").href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/left';\r\n");
      out.write("\t\t\t\t\t\t\twindow.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/left';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-default navbar-fixed-top header\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#header-navbar-collapse\"\r\n");
      out.write("\t\t\t\taria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t<span class=\"sr-only\">e享课堂</span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\"> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/logo.png\"\r\n");
      out.write("\t\t\t\twidth=\"90px\" height=\"50px\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"header-navbar-collapse\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/courseListAll\">课程</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"#\" onclick=\"pleaseLogin()\" id=\"personCenter\">个人中心</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/demand\">需求热搜</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/aboutus.jsp\">关于我们</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("\t<div class=\"subbox\">\r\n");
      out.write("\t\t<!--左侧部分-->\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t<!--左侧部分-->\r\n");
      out.write("\t\t<div class=\"left180\">\r\n");
      out.write("\t\t\t<div class=\"grtx\">\r\n");
      out.write("\t\t\t\t<div class=\"grimg\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${leftUser.photo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"margin-left:4px;margin-top:5px;\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"grname\">\r\n");
      out.write("\t\t\t\t\t<span style=\"font-size:14px;color:#03ab81;font-weight:bold;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${leftUser.nickName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<ul class=\"menu1\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/findInfo\"><em>信息设置</em></a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul class=\"menu1\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/join\"><em>学习课程</em></a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul class=\"menu1\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/upload\"><em>上传课程</em></a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul class=\"menu1\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/relatecomment/find\"><em>与我相关</em></a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul class=\"menu1\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/relate\"><em>系统通知</em></a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul class=\"menu1\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/finance\"><em>零钱明细</em></a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul class=\"menu1\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/collection\"><em>我的收藏</em></a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul class=\"menu1\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/follow\"><em>关&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;注</em></a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>");
      out.write("\r\n");
      out.write("\t\t<!--右侧部分-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"right840\">\r\n");
      out.write("\t\t\t\t<div class=\"title6\">\r\n");
      out.write("\t\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"application.html\" class=\"on\">上传课程</a>\r\n");
      out.write("\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"display\" id=\"courseId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.courseId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<div class=\"title12\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/scimg2.jpg\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<form action=\"\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t    <a class=\"opts_btn\" href=\"JavaScript:void(0)\">\r\n");
      out.write("\t\t\t\t\t        <label id=\"opst_txt\">选择上传文件</label><input type=\"file\" id=\"oFile\" class=\"oFile\"  name=\"file\" onchange=\"FileChangeFn(event)\" accept=\"video/mp4,video/flv\">\r\n");
      out.write("\t\t\t\t\t        \r\n");
      out.write("\t\t\t\t\t    </a>\r\n");
      out.write("\t\t\t\t\t    <span id=\"uploadSpan\" style=\"font-size:12px;color:red\"></span>\r\n");
      out.write("\t\t\t\t\t     <!--上传速度显示-->\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t    <label id=\"file_size\"></label>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t    <label id=\"file_type\"></label>\r\n");
      out.write("\t\t\t\t\t    <br>\r\n");
      out.write("\t\t\t\t\t    <label id=\"file_time\"></label>\r\n");
      out.write("\t\t\t\t\t    <div id=\"file_box\"></div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"speed_box\" style=\"width: 500px;margin-top: 20px;\">\r\n");
      out.write("\t\t\t\t\t        <div id=\"speed\">0%</div>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t \t<div class=\"videoinfo\" style=\"font-size: 15px; height: 210px; margin-bottom: 0;width: 510px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t\t\t<font>*</font>&nbsp;&nbsp;&nbsp;<b>文件目录:</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"catalog\" id=\"catalog\" style=\"width: 400px; height: 50px; \" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"send_btn\" onclick=\"UploadFileFn(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\" style=\"margin-right: 10px;\">开始上传文件</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t    <div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t</form>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"clear\" style=\"height: 30px;\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-xs-6 col-sm-3 col-md-8 footer-col footer-a\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.html\" target=\"_blank\"\r\n");
      out.write("\t\t\t\t\tclass=\"col-md-2  \">关于我们</a> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/privacy/index.html\"\r\n");
      out.write("\t\t\t\t\ttarget=\"_blank\" class=\"col-md-2  \">合作伙伴</a> <a\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.html\" target=\"_blank\"\r\n");
      out.write("\t\t\t\t\tclass=\"col-md-2  \">联系客服</a> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/paths/index.html\"\r\n");
      out.write("\t\t\t\t\ttarget=\"_blank\" class=\"col-md-2  \">联系我们</a> <a\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.html\" target=\"_blank\" class=\"col-md-2  \">隐私条款</a>\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.html\" target=\"_blank\"\r\n");
      out.write("\t\t\t\t\tclass=\"col-md-2  \">法律声明</a> <br> \r\n");
      out.write("\t\t\t\t<div class=\"copyright\" style=\"width: 800px;\"><span>Copyright\r\n");
      out.write("\t\t\t\t\t@3013-3016 实验楼在线教育</span> <span class=\"ver-line\"> | </span> \r\n");
      out.write("\t\t\t\t\t<span>蜀ICP备13019763号</span></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 clearfix footer-col footer-d\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-3 \">\r\n");
      out.write("\t\t\t\t\t<div class=\"social-item footer-weixin-item footer-img\"\r\n");
      out.write("\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-weixin\"></i>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-weixin\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/footer-weixin.png\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"social-item footer-qq-item  footer-img\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-qq\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"social-item footer-weibo-item  footer-img\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://weibo.com/shiyanlou3013\" target=\"_blank\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-weibo\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /upload2.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /upload2.jsp(4,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /header.jsp(46,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginFlag=='0'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t<div class=\"navbar-right btns\" id=\"loginhidden\">\r\n");
        out.write("\t\t\t\t\t<a class=\"btn btn-default navbar-btn sign-in\" data-sign=\"signin\"\r\n");
        out.write("\t\t\t\t\t\thref=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/#sign-modal\" data-toggle=\"modal\">登录</a> <a\r\n");
        out.write("\t\t\t\t\t\tclass=\"btn btn-default navbar-btn sign-up\" data-sign=\"signup\"\r\n");
        out.write("\t\t\t\t\t\thref=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/#sign-modal\" data-toggle=\"modal\">注册</a>\r\n");
        out.write("\t\t\t\t</div>\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /header.jsp(55,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginFlag=='1'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t<div class=\"navbar-right btns\" id=\"loginshow\" style=\"float:right;\">\r\n");
        out.write("\t\t\t\t\t<img src=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write('/');
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.photo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" style=\"width: 35px; height: 35px\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/#\">\r\n");
        out.write("\t\t\t\t\t<a class=\"btn btn-default navbar-btn sign-up\" href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/quit\">退出</a>\r\n");
        out.write("\t\t\t\t</div>\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
